[aws]
access_key_id     = "AKIAxxxxxxxxxxxxxxxx"
secret_access_key = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
region            = "us-east-1"
bucket            = "your-bucket-name"
prefix            = "ingestion"

[app]
# optional knobs
max_file_mb       = 50
allow_xlsx        = true
