# Example .streamlit/secrets.toml (S3-only, safe to be empty)
# You can deploy with nothing in here; the app won’t crash.

[aws]
# access_key_id     = "AKIAxxxxxxxxxxxxxxxx"
# secret_access_key = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
# region            = "us-east-1"
# bucket            = "your-bucket-name"
# prefix            = "ingestion"

[app]
max_file_mb = 50
allow_xlsx  = true
